"""empty message

Revision ID: 1dc73e27327c
Revises: 
Create Date: 2020-05-02 17:22:40.733804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc73e27327c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('cod_categoria', sa.Integer(), nullable=True),
    sa.Column('cod_equipe', sa.Integer(), nullable=True),
    sa.Column('cod_foto', sa.Integer(), nullable=True),
    sa.Column('cod_ramo', sa.Integer(), nullable=True),
    sa.Column('cod_ramo_adulto', sa.Integer(), nullable=True),
    sa.Column('cod_segunda_categoria', sa.Integer(), nullable=True),
    sa.Column('cod_terceira_categoria', sa.Integer(), nullable=True),
    sa.Column('dt_nascimento', sa.Date(), nullable=True),
    sa.Column('dt_validade', sa.Date(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('nome_abreviado', sa.String(length=80), nullable=True),
    sa.Column('linha_formacao', sa.String(length=30), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('numero_digito', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('Cerimonia', 'Cancao', 'Intervalo', 'QuebraGelo', 'Jogo', name='tipoatividade'), nullable=True),
    sa.Column('nome', sa.String(length=180), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('areas', sa.Enum('FISICO', 'INTELECTUAL', 'CARATER', 'AFETIVO', 'SOCIAL', 'ESPIRITUAL', name='areadesenvolvimento'), nullable=True),
    sa.Column('progressoes', sa.String(length=20), nullable=True),
    sa.Column('desenvolvimento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_escoteiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('codigo_regiao', sa.String(length=2), nullable=True),
    sa.Column('nome', sa.String(length=180), nullable=True),
    sa.Column('modalidade', sa.Enum('BASICO', 'MAR', 'AR', name='codigomodalidade'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('param',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('param_name', sa.String(length=30), nullable=True),
    sa.Column('param_value', sa.String(length=180), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.Enum('FISICO', 'INTELECTUAL', 'CARATER', 'AFETIVO', 'SOCIAL', 'ESPIRITUAL', name='areadesenvolvimento'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('cod_tipo_secao', sa.Enum('ALCATEIA', 'TROPA_ESCOTEIRA', 'TROPA_SENIOR', 'CLA_PIONEIRO', name='tiposecao'), nullable=True),
    sa.Column('cod_grupo', sa.Integer(), nullable=True),
    sa.Column('cod_regiao', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=140), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('verified_email', sa.Boolean(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=40), nullable=True),
    sa.Column('codigo_associado', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=140), nullable=True),
    sa.Column('codigo_grupo', sa.Integer(), nullable=True),
    sa.Column('nome_grupo', sa.String(length=140), nullable=True),
    sa.Column('codigo_regiao', sa.String(length=2), nullable=True),
    sa.Column('codigo_secao', sa.Integer(), nullable=True),
    sa.Column('authorization', sa.String(length=64), nullable=True),
    sa.Column('auth_valid_until', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('termino', sa.DateTime(), nullable=True),
    sa.Column('recursos_materiais', sa.Text(), nullable=True),
    sa.Column('preparacao_previa', sa.Text(), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_escoteiro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontro_atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encontro_id', sa.Integer(), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], ),
    sa.ForeignKeyConstraint(['encontro_id'], ['encontro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontro_escotista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encontro_id', sa.Integer(), nullable=True),
    sa.Column('escotista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encontro_id'], ['encontro.id'], ),
    sa.ForeignKeyConstraint(['escotista_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encontro_escotista')
    op.drop_table('encontro_atividade')
    op.drop_table('encontro')
    op.drop_table('user')
    op.drop_table('secao')
    op.drop_table('product')
    op.drop_table('param')
    op.drop_table('grupo_escoteiro')
    op.drop_table('atividade')
    op.drop_table('associado')
    # ### end Alembic commands ###
