"""empty message

Revision ID: 3863839393f1
Revises: a832aaed8516
Create Date: 2020-02-16 22:08:55.102304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3863839393f1'
down_revision = 'a832aaed8516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MAPPA__sub_secao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('codigoSecao', sa.Integer(), nullable=True),
    sa.Column('id_lider', sa.Integer(), nullable=True),
    sa.Column('id_sublider', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.add_column('user', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ativo')
    op.drop_table('MAPPA__sub_secao')
    # ### end Alembic commands ###
