"""empty message

Revision ID: 3b03bc761948
Revises: f195abdeec82
Create Date: 2020-01-19 11:49:39.392404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b03bc761948'
down_revision = 'f195abdeec82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encontro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_escoteiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('codigo_regiao', sa.String(length=2), nullable=True),
    sa.Column('nome', sa.String(length=180), nullable=True),
    sa.Column('modalidade', sa.Enum('BASICO', 'MAR', 'AR', name='codigomodalidade'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo_escoteiro')
    op.drop_table('encontro')
    # ### end Alembic commands ###
