"""empty message

Revision ID: 460e09d32072
Revises: c16eab040d18
Create Date: 2020-01-05 00:55:20.977044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460e09d32072'
down_revision = 'c16eab040d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sexo', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sexo')
    # ### end Alembic commands ###
