"""empty message

Revision ID: f195abdeec82
Revises: 
Create Date: 2020-01-19 11:43:07.436987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f195abdeec82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MAPPA__progressao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=180), nullable=True),
    sa.Column('codigoUeb', sa.String(length=4), nullable=True),
    sa.Column('ordenacao', sa.Integer(), nullable=True),
    sa.Column('codigoCaminho', sa.Integer(), nullable=True),
    sa.Column('codigoDesenvolvimento', sa.Integer(), nullable=True),
    sa.Column('codigoCompetencia', sa.Integer(), nullable=True),
    sa.Column('segmento', sa.String(length=60), nullable=True),
    sa.Column('ramo', sa.Enum('ALCATEIA', 'TROPA_ESCOTEIRA', 'TROPA_SENIOR', 'CLA_PIONEIRO', name='tiposecao'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('Cerimonia', 'Cancao', 'Intervalo', 'QuebraGelo', 'Jogo', name='tipoatividade'), nullable=True),
    sa.Column('nome', sa.String(length=180), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('areas', sa.Enum('FISICO', 'INTELECTUAL', 'CARATER', 'AFETIVO', 'SOCIAL', 'ESPIRITUAL', name='areadesenvolvimento'), nullable=True),
    sa.Column('progressoes', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.Enum('FISICO', 'INTELECTUAL', 'CARATER', 'AFETIVO', 'SOCIAL', 'ESPIRITUAL', name='areadesenvolvimento'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=140), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('codigo_associado', sa.Integer(), nullable=True),
    sa.Column('codigo_grupo', sa.Integer(), nullable=True),
    sa.Column('codigo_regiao', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('atividade')
    op.drop_table('MAPPA__progressao')
    # ### end Alembic commands ###
